import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../core/share/share_service.dart';
import '../../../l10n/app_localizations.dart';

/// Screen for viewing a shared note.
///
/// Supports two modes:
/// 1. **Server share**: The share ID is a hex string. The viewer fetches the
///    encrypted blob from the server via GET /api/v1/share/{id}, then decrypts
///    locally using the key from the URL fragment.
/// 2. **Self-contained share**: The share ID is a base64url-encoded payload
///    containing the encrypted data inline. No server round-trip needed.
///
/// Accessible via deep link or URL: /share/{idOrPayload}#{key}
/// The key is extracted from the URL fragment and never sent to the server.
///
/// If the share is password-protected (fragment is "pwd" or absent), a
/// password input is shown before decryption can proceed.
class SharedNoteViewer extends ConsumerStatefulWidget {
  /// The share ID (hex string for server shares) or encrypted payload
  /// (base64url-encoded for self-contained shares).
  final String shareId;

  /// The decryption key from the URL fragment (base64url-encoded), or null.
  /// If null and the share is password-protected, a password dialog is shown.
  final String? shareKeyFragment;

  const SharedNoteViewer({
    super.key,
    required this.shareId,
    this.shareKeyFragment,
  });

  @override
  ConsumerState<SharedNoteViewer> createState() => _SharedNoteViewerState();
}

class _SharedNoteViewerState extends ConsumerState<SharedNoteViewer> {
  DecryptedSharedNote? _decryptedNote;
  bool _isDecrypting = true;
  String? _error;
  bool? _isServerShare;

  final _passwordController = TextEditingController();

  /// Whether the share link indicates password protection.
  bool get _isPasswordProtected => widget.shareKeyFragment == null;

  @override
  void initState() {
    super.initState();
    _tryDecrypt();
  }

  @override
  void dispose() {
    _passwordController.dispose();
    super.dispose();
  }

  /// Detect whether the share ID is a server share (hex string) or a
  /// self-contained payload (base64url blob).
  ///
  /// Server share IDs are 32-char hex strings generated by the backend.
  /// Self-contained payloads are longer base64url-encoded blobs.
  bool _detectIsServerShare(String shareId) {
    // Server IDs are 32-char hex strings (16 bytes).
    // Self-contained payloads are longer base64url strings.
    final hexPattern = RegExp(r'^[0-9a-f]{32}$');
    return hexPattern.hasMatch(shareId);
  }

  /// Attempt to decrypt the shared note.
  ///
  /// For server shares: fetch the encrypted data from the API first, then
  /// decrypt locally with the key from the URL fragment.
  /// For self-contained shares: decrypt directly from the embedded payload.
  Future<void> _tryDecrypt() async {
    // If password-protected, show password input instead.
    if (_isPasswordProtected) {
      setState(() {
        _isDecrypting = false;
      });
      return;
    }

    setState(() {
      _isDecrypting = true;
      _error = null;
    });

    try {
      final shareService = ref.read(shareServiceProvider);
      final isServer = _detectIsServerShare(widget.shareId);
      _isServerShare = isServer;

      final DecryptedSharedNote decrypted;
      if (isServer) {
        // Server share: fetch from server, then decrypt.
        decrypted = await shareService.decryptServerSharedNote(
          shareId: widget.shareId,
          key: widget.shareKeyFragment,
        );
      } else {
        // Self-contained share: decrypt from embedded payload.
        decrypted = await shareService.decryptSharedNote(
          payload: widget.shareId,
          key: widget.shareKeyFragment,
        );
      }

      if (mounted) {
        setState(() {
          _decryptedNote = decrypted;
          _isDecrypting = false;
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _error = 'decrypt_failed';
          _isDecrypting = false;
        });
      }
    }
  }

  Future<void> _decryptWithPassword() async {
    if (_passwordController.text.isEmpty) return;

    setState(() {
      _isDecrypting = true;
      _error = null;
    });

    try {
      final shareService = ref.read(shareServiceProvider);
      final isServer = _isServerShare ?? _detectIsServerShare(widget.shareId);

      final DecryptedSharedNote decrypted;
      if (isServer) {
        // Server share: fetch from server, decrypt with password.
        decrypted = await shareService.decryptServerSharedNote(
          shareId: widget.shareId,
          password: _passwordController.text,
        );
      } else {
        // Self-contained share: decrypt from embedded payload with password.
        decrypted = await shareService.decryptSharedNote(
          payload: widget.shareId,
          password: _passwordController.text,
        );
      }

      if (mounted) {
        setState(() {
          _decryptedNote = decrypted;
          _isDecrypting = false;
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _error = 'incorrect_password';
          _isDecrypting = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    final theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(
        title: Text(l10n.shareNote),
      ),
      body: _buildBody(theme),
    );
  }

  /// Resolve the internal error sentinel to a localized user-facing string.
  String _resolveError(AppLocalizations l10n) {
    return switch (_error) {
      'decrypt_failed' => l10n.decryptFailed,
      'incorrect_password' => l10n.incorrectPassword,
      _ => _error ?? l10n.couldNotDecryptSharedNote,
    };
  }

  Widget _buildBody(ThemeData theme) {
    final l10n = AppLocalizations.of(context)!;
    if (_isDecrypting) {
      return Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const CircularProgressIndicator(),
            const SizedBox(height: 16),
            Text(l10n.decryptingSharedNote),
          ],
        ),
      );
    }

    if (_decryptedNote != null) {
      return _buildDecryptedNote(theme);
    }

    if (_isPasswordProtected) {
      return _buildPasswordInput(theme);
    }

    // Non-password share that failed to decrypt.
    return _buildErrorState(theme);
  }

  Widget _buildErrorState(ThemeData theme) {
    final l10n = AppLocalizations.of(context)!;
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(32),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(Icons.link_off, size: 64, color: theme.colorScheme.error),
            const SizedBox(height: 16),
            Text(
              _resolveError(l10n),
              style: theme.textTheme.titleMedium,
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 8),
            Text(
              l10n.linkCorruptedExpired,
              style: TextStyle(color: Colors.grey.shade600, fontSize: 14),
              textAlign: TextAlign.center,
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildPasswordInput(ThemeData theme) {
    final l10n = AppLocalizations.of(context)!;
    return Padding(
      padding: const EdgeInsets.all(32),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(Icons.lock_outline, size: 64, color: theme.colorScheme.primary),
          const SizedBox(height: 16),
          Text(
            l10n.passwordRequiredTitle,
            style: theme.textTheme.titleLarge,
          ),
          const SizedBox(height: 8),
          Text(
            l10n.enterPasswordToView,
            style: TextStyle(color: Colors.grey.shade600, fontSize: 14),
            textAlign: TextAlign.center,
          ),
          const SizedBox(height: 24),
          TextField(
            controller: _passwordController,
            decoration: InputDecoration(
              labelText: l10n.password,
              border: const OutlineInputBorder(),
              prefixIcon: const Icon(Icons.lock_outline),
              errorText: _error != null ? _resolveError(l10n) : null,
            ),
            obscureText: true,
            autofocus: true,
            onSubmitted: (_) => _decryptWithPassword(),
          ),
          const SizedBox(height: 16),
          SizedBox(
            width: double.infinity,
            child: FilledButton(
              onPressed: _isDecrypting ? null : _decryptWithPassword,
              child: _isDecrypting
                  ? const SizedBox(
                      width: 20,
                      height: 20,
                      child: CircularProgressIndicator(strokeWidth: 2),
                    )
                  : Text(l10n.unlock),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildDecryptedNote(ThemeData theme) {
    final l10n = AppLocalizations.of(context)!;
    final note = _decryptedNote!;

    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Title
          Text(
            note.title,
            style: theme.textTheme.headlineSmall?.copyWith(
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 8),

          // Metadata row
          Row(
            children: [
              Icon(
                Icons.visibility_outlined,
                size: 14,
                color: Colors.grey.shade500,
              ),
              const SizedBox(width: 4),
              Text(
                _isServerShare == true
                    ? l10n.sharedViaLink
                    : l10n.sharedNote,
                style: TextStyle(fontSize: 12, color: Colors.grey.shade500),
              ),
            ],
          ),
          const Divider(height: 32),

          // Content with markdown rendering (same style as note_detail_screen).
          MarkdownBody(
            data: note.content,
            selectable: true,
            styleSheet: MarkdownStyleSheet(
              p: const TextStyle(fontSize: 16, height: 1.6),
              h1: const TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
              h2: const TextStyle(fontSize: 22, fontWeight: FontWeight.bold),
              h3: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
              code: TextStyle(
                fontSize: 14,
                backgroundColor:
                    theme.colorScheme.surfaceContainerHighest,
              ),
              blockquote: TextStyle(
                color: Colors.grey.shade600,
                fontStyle: FontStyle.italic,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
