import 'dart:async';

import 'package:flutter/widgets.dart' show TextEditingController, TextSelection;

import 'crdt_text.dart';

/// An operation produced by the CRDT editor controller.
///
/// Wraps the CRDT-level data (insert nodes or delete IDs) with enough
/// metadata for the broadcast layer to serialize and send over the wire.
class CrdtEditorOp {
  /// Inserted nodes (non-null for insert operations).
  final List<RGANode>? insertedNodes;

  /// Deleted node IDs (non-null for delete operations).
  final List<String>? deletedNodeIds;

  const CrdtEditorOp({this.insertedNodes, this.deletedNodeIds});

  bool get isInsert => insertedNodes != null;
  bool get isDelete => deletedNodeIds != null;
}

/// Bridges a [TextEditingController] with a [CRDTText] document.
///
/// Listens to local text changes, computes a diff, and converts it into
/// CRDT insert/delete operations. Remote operations are applied to the
/// CRDT document and then reflected in the text controller without
/// triggering the local change listener (via [_applyingRemote] flag).
///
/// Usage:
///   final controller = CrdtEditorController(crdt: myCrdtText);
///   textField = TextField(controller: controller.textController);
///   controller.changes.listen((op) => broadcast(op));
///   controller.applyRemoteOps(remoteNodes);
class CrdtEditorController {
  final CRDTText crdt;
  final TextEditingController textController = TextEditingController();

  final _changesController = StreamController<CrdtEditorOp>.broadcast();

  /// Whether we are currently applying a remote update to the text
  /// controller. When true, the local listener is suppressed so that
  /// remote changes are not re-broadcast as local edits.
  bool _applyingRemote = false;

  /// The text value before the latest local change, used for diffing.
  String _previousText = '';

  CrdtEditorController({required this.crdt}) {
    // Initialize the text controller from the CRDT state.
    _previousText = crdt.text;
    textController.text = _previousText;

    textController.addListener(_onLocalEdit);
  }

  /// Stream of CRDT operations generated by local edits.
  /// The broadcast layer should listen to this and send ops over WebSocket.
  Stream<CrdtEditorOp> get changes => _changesController.stream;

  /// Apply remote CRDT operations received from the network.
  ///
  /// Updates the CRDT document, computes the new text, and applies it
  /// to the text controller while preserving the cursor position.
  void applyRemoteOps(List<RGANode> remoteOps) {
    if (remoteOps.isEmpty) return;

    final oldText = crdt.text;
    crdt.merge(remoteOps);
    final newText = crdt.text;

    if (oldText == newText) return;

    _applyingRemote = true;
    try {
      _updateTextPreservingCursor(newText);
    } finally {
      _applyingRemote = false;
      _previousText = newText;
    }
  }

  /// Apply a single remote insert operation.
  void applyRemoteInsert(RGANode node) {
    final oldText = crdt.text;
    final alreadyPresent = crdt.remoteInsert(node);
    if (alreadyPresent) return;

    final newText = crdt.text;
    if (oldText == newText) return;

    _applyingRemote = true;
    try {
      _updateTextPreservingCursor(newText);
    } finally {
      _applyingRemote = false;
      _previousText = newText;
    }
  }

  /// Apply a single remote delete operation.
  void applyRemoteDelete(String nodeId) {
    final oldText = crdt.text;
    crdt.remoteDelete(nodeId);
    final newText = crdt.text;

    if (oldText == newText) return;

    _applyingRemote = true;
    try {
      _updateTextPreservingCursor(newText);
    } finally {
      _applyingRemote = false;
      _previousText = newText;
    }
  }

  /// Replace the entire CRDT content with [text] (used when loading from
  /// persistence or initializing). This is a local-only operation; no
  /// CRDT ops are emitted.
  void initializeFromText(String text) {
    _applyingRemote = true;
    try {
      textController.text = text;
    } finally {
      _applyingRemote = false;
    }
    _previousText = text;
  }

  /// Clean up resources. Must be called when the controller is no longer
  /// needed (e.g. in the widget's dispose method).
  void dispose() {
    textController.removeListener(_onLocalEdit);
    textController.dispose();
    _changesController.close();
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  /// Called whenever the text controller value changes. If the change was
  /// local (not caused by remote application), compute a diff and emit
  /// the corresponding CRDT operations.
  void _onLocalEdit() {
    if (_applyingRemote) return;

    final newText = textController.text;
    final oldText = _previousText;

    if (newText == oldText) return;

    final diff = _computeDiff(oldText, newText);
    if (diff == null) {
      // Could not compute a clean diff (e.g. simultaneous insert + delete).
      // Fall back to replacing the entire text.
      _handleReplace(oldText, newText);
    } else {
      _applyDiffToCrdt(diff);
    }

    _previousText = newText;
  }

  /// Compute a simple diff between [oldText] and [newText].
  ///
  /// Returns null if the diff is not a simple insert or delete (e.g.
  /// replacement). In that case the caller should fall back to a full
  /// replace strategy.
  _TextDiff? _computeDiff(String oldText, String newText) {
    if (oldText == newText) return null;

    // Check for a pure insert: newText is oldText with characters added
    // at some position.
    if (newText.length > oldText.length) {
      final insertResult = _findInsert(oldText, newText);
      if (insertResult != null) return insertResult;
    }

    // Check for a pure delete: newText is oldText with characters removed.
    if (newText.length < oldText.length) {
      final deleteResult = _findDelete(oldText, newText);
      if (deleteResult != null) return deleteResult;
    }

    // Could be a replace (simultaneous delete + insert at same position).
    // Try to decompose it as a delete followed by an insert.
    return _findReplace(oldText, newText);
  }

  /// Try to find a pure insertion position.
  _TextDiff? _findInsert(String oldText, String newText) {
    final oldLen = oldText.length;
    final newLen = newText.length;

    // Find the common prefix length.
    var prefixLen = 0;
    while (prefixLen < oldLen &&
        prefixLen < newLen &&
        oldText[prefixLen] == newText[prefixLen]) {
      prefixLen++;
    }

    // Find the common suffix length.
    var suffixLen = 0;
    while (suffixLen < oldLen - prefixLen &&
        suffixLen < newLen - prefixLen &&
        oldText[oldLen - 1 - suffixLen] == newText[newLen - 1 - suffixLen]) {
      suffixLen++;
    }

    final insertedLen = newLen - prefixLen - suffixLen;
    if (prefixLen + suffixLen == oldLen && insertedLen == newLen - oldLen) {
      return _TextDiff(
        type: _DiffType.insert,
        index: prefixLen,
        text: newText.substring(prefixLen, prefixLen + insertedLen),
      );
    }
    return null;
  }

  /// Try to find a pure deletion position.
  _TextDiff? _findDelete(String oldText, String newText) {
    final oldLen = oldText.length;
    final newLen = newText.length;

    var prefixLen = 0;
    while (prefixLen < newLen &&
        prefixLen < oldLen &&
        oldText[prefixLen] == newText[prefixLen]) {
      prefixLen++;
    }

    var suffixLen = 0;
    while (suffixLen < newLen - prefixLen &&
        suffixLen < oldLen - prefixLen &&
        oldText[oldLen - 1 - suffixLen] == newText[newLen - 1 - suffixLen]) {
      suffixLen++;
    }

    final deletedLen = oldLen - prefixLen - suffixLen;
    if (prefixLen + suffixLen == newLen && deletedLen == oldLen - newLen) {
      return _TextDiff(
        type: _DiffType.delete,
        index: prefixLen,
        text: oldText.substring(prefixLen, prefixLen + deletedLen),
      );
    }
    return null;
  }

  /// Decompose a replace as delete + insert.
  _TextDiff? _findReplace(String oldText, String newText) {
    // Find the common prefix.
    var prefixLen = 0;
    while (prefixLen < oldText.length &&
        prefixLen < newText.length &&
        oldText[prefixLen] == newText[prefixLen]) {
      prefixLen++;
    }

    // Find the common suffix (not overlapping the prefix).
    var suffixLen = 0;
    while (suffixLen < oldText.length - prefixLen &&
        suffixLen < newText.length - prefixLen &&
        oldText[oldText.length - 1 - suffixLen] ==
            newText[newText.length - 1 - suffixLen]) {
      suffixLen++;
    }

    final deletedLen = oldText.length - prefixLen - suffixLen;
    final insertedLen = newText.length - prefixLen - suffixLen;

    return _TextDiff(
      type: _DiffType.replace,
      index: prefixLen,
      deletedText: deletedLen > 0
          ? oldText.substring(prefixLen, prefixLen + deletedLen)
          : null,
      text: insertedLen > 0
          ? newText.substring(prefixLen, prefixLen + insertedLen)
          : null,
    );
  }

  /// Apply a diff to the CRDT and emit the resulting operations.
  void _applyDiffToCrdt(_TextDiff diff) {
    switch (diff.type) {
      case _DiffType.insert:
        if (diff.text != null && diff.text!.isNotEmpty) {
          final nodes = crdt.localInsert(diff.index, diff.text!);
          _emit(CrdtEditorOp(insertedNodes: nodes));
        }
      case _DiffType.delete:
        if (diff.text != null && diff.text!.isNotEmpty) {
          final deletedIds = crdt.localDelete(diff.index, diff.text!.length);
          _emit(CrdtEditorOp(deletedNodeIds: deletedIds));
        }
      case _DiffType.replace:
        // First delete, then insert.
        if (diff.deletedText != null && diff.deletedText!.isNotEmpty) {
          final deletedIds =
              crdt.localDelete(diff.index, diff.deletedText!.length);
          _emit(CrdtEditorOp(deletedNodeIds: deletedIds));
        }
        if (diff.text != null && diff.text!.isNotEmpty) {
          // After deletion, the insert index stays the same (deletion shifts
          // text left, but insert goes at the same visible position).
          final nodes = crdt.localInsert(diff.index, diff.text!);
          _emit(CrdtEditorOp(insertedNodes: nodes));
        }
    }
  }

  /// Handle a full text replacement by deleting all existing content and
  /// inserting the new content. Used when the diff cannot be decomposed
  /// into a simple insert or delete.
  void _handleReplace(String oldText, String newText) {
    // Delete all existing content.
    if (oldText.isNotEmpty) {
      final deletedIds = crdt.localDelete(0, oldText.length);
      _emit(CrdtEditorOp(deletedNodeIds: deletedIds));
    }
    // Insert new content.
    if (newText.isNotEmpty) {
      final nodes = crdt.localInsert(0, newText);
      _emit(CrdtEditorOp(insertedNodes: nodes));
    }
  }

  /// Emit an operation to the changes stream if the stream is still open.
  void _emit(CrdtEditorOp op) {
    if (!_changesController.isClosed) {
      _changesController.add(op);
    }
  }

  /// Update the text controller value while attempting to keep the cursor
  /// at the correct logical position relative to the new text.
  void _updateTextPreservingCursor(String newText) {
    final oldSelection = textController.selection;
    final oldText = textController.text;
    final oldCursorPos = oldSelection.baseOffset;

    textController.text = newText;

    // Compute the new cursor position. The cursor should stay at the same
    // offset unless text was inserted or deleted before it.
    var newCursorPos = oldCursorPos;

    // Clamp to the new text length.
    newCursorPos = newCursorPos.clamp(0, newText.length);

    if (oldCursorPos >= 0 && oldCursorPos <= oldText.length) {
      // If text was inserted before the cursor, shift the cursor right.
      // If text was deleted before the cursor, shift the cursor left.
      final delta = newText.length - oldText.length;
      if (oldCursorPos >= oldText.length) {
        // Cursor was at the end: keep it at the end.
        newCursorPos = newText.length;
      } else {
        // Try to find the new position by looking for the text that was
        // immediately after the cursor in the old text.
        final afterCursor = oldText.substring(oldCursorPos);
        final afterIndex = newText.indexOf(afterCursor);
        if (afterIndex >= 0) {
          newCursorPos = afterIndex;
        } else {
          // Fallback: shift by the overall delta, clamped.
          newCursorPos = (oldCursorPos + delta).clamp(0, newText.length);
        }
      }
    }

    newCursorPos = newCursorPos.clamp(0, newText.length);

    textController.selection = TextSelection.collapsed(offset: newCursorPos);
  }
}

// ---------------------------------------------------------------------------
// Diff types
// ---------------------------------------------------------------------------

enum _DiffType { insert, delete, replace }

class _TextDiff {
  final _DiffType type;
  final int index;

  /// For insert: the inserted text. For delete: the deleted text.
  /// For replace: the inserted text (deletedText is separate).
  final String? text;

  /// Only for replace: the deleted text.
  final String? deletedText;

  const _TextDiff({
    required this.type,
    required this.index,
    this.text,
    this.deletedText,
  });
}
